DROP TABLE IF EXISTS users, categories, locations, events, compilations, event_compilations, requests;

CREATE TABLE IF NOT EXISTS users
(
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name    VARCHAR(255) NOT NULL,
    email   VARCHAR(255) NOT NULL
);
CREATE TABLE IF NOT EXISTS categories
(
    category_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(255) NOT NULL
);
CREATE TABLE IF NOT EXISTS locations
(
    location_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lat         float NOT NULL,
    lon         float NOT NULL
);
CREATE TABLE IF NOT EXISTS events
(
    event_id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    annotation         VARCHAR(2550) NOT NULL,
    category_id        BIGINT REFERENCES categories (category_id) ON DELETE CASCADE,
    confirmed_requests BIGINT,
    created_on         TIMESTAMP WITHOUT TIME ZONE,
    description        VARCHAR(2550) NOT NULL,
    event_date         TIMESTAMP WITHOUT TIME ZONE,
    initiator_id       BIGINT REFERENCES users (user_id) ON DELETE CASCADE,
    location_id        BIGINT REFERENCES locations (location_id) ON DELETE CASCADE,
    paid               BOOLEAN,
    participant_limit  BIGINT,
    published_on       TIMESTAMP WITHOUT TIME ZONE,
    request_moderation BOOLEAN       NOT NULL,
    state              VARCHAR(255)  NOT NULL,
    title              VARCHAR(2550) NOT NULL,
    views              BIGINT
);
CREATE TABLE IF NOT EXISTS compilations
(
    compilation_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pinned         BOOLEAN,
    title          VARCHAR(255)
);
CREATE TABLE IF NOT EXISTS event_compilations
(
    compilation_id BIGINT REFERENCES compilations (compilation_id) ON DELETE CASCADE,
    event_id       BIGINT REFERENCES events (event_id) ON DELETE CASCADE,
    PRIMARY KEY (compilation_id, event_id)
);
CREATE TABLE IF NOT EXISTS requests
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    requester_id BIGINT REFERENCES users (user_id),
    event_id     BIGINT REFERENCES events (event_id),
    status       VARCHAR,
    created      TIMESTAMP WITHOUT TIME ZONE
);

