DROP TABLE IF EXISTS users, categories, locations, events, compilations;

CREATE TABLE IF NOT EXISTS users
(
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    name    VARCHAR(255)                                        NOT NULL,
    email   VARCHAR(255)                                        NOT NULL
);
CREATE TABLE IF NOT EXISTS categories
(
    category_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    name        VARCHAR(255)                                        NOT NULL
);
CREATE TABLE IF NOT EXISTS locations
(
    location_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    lat         float                                               NOT NULL,
    lon         float                                               NOT NULL
);
CREATE TABLE IF NOT EXISTS events
(
    event_id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    annotation         VARCHAR(255)                                        NOT NULL,
    category_id        BIGINT,
    confirmed_requests BIGINT,
    created_on         TIME,
    description        VARCHAR(255),
    event_date         TIME,
    initiator_id       BIGINT,
    location_id        BIGINT,
    paid               BOOLEAN,
    participant_limit  BIGINT,
    published_on       TIME,
    request_moderation BOOLEAN,
    state_id           VARCHAR(255),
    title              VARCHAR(255),
    views              BIGINT
);
CREATE TABLE IF NOT EXISTS compilations
(
    compilation_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    pinned         BOOLEAN,
    title          VARCHAR(255)
);